<?php echo $this->doctype() . "\n" ?>
<html>
<head>
<?php
echo $this->headMeta()->setIndent('    ') . "\n";
echo $this->headTitle('ZF Pubsubhubbub Aggregator')
    ->setSeparator(' / ')->setIndent('    ') . "\n";
echo $this->headLink()->setIndent('    ')
    ->appendStylesheet('http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css')
    ->appendStylesheet('http://yui.yahooapis.com/2.7.0/build/base/base-min.css')
    ->appendStylesheet($this->includeModifiedDate('/css/style.css')) . "\n    ";
echo $this->headScript()->prependFile(
    'http://html5shiv.googlecode.com/svn/trunk/html5.js',
    'text/javascript',
    array('conditional'=>'IE')) . "\n";
?>
</head>
<body>
    <div id="doc" class="yui-t1">

        <header id="hd" role="banner">
            <hgroup>
                <h1><a href="/">ZF Pubsubhubbub Aggregator</a></h1>
                <h2>Zend_Feed_Pubsubhubbub Test Application</h2>
            </hgroup>
            <nav role="navigation">
                <ul>
                    <li><a href="/">Home</a></li>
                    <li><a href="#">About</a></li>
                </ul>
            </nav>
        </header>

        <div id="bd">
            <div id="yui-main">
                <div class="yui-b" role="main">
                    <section id ="content" class="yui-g">
                        <?php echo $this->layout()->content ?>
                    </section>
                </div>
            </div>
            <section class="yui-b">
                <nav role="navigation" aria-labelledby="leftnav-label">
                    <h2 id="leftnav-label">External Links</h2>
                    <ul>
                        <li><a href="http://www.survivethedeepend.com">Survive The Deep End</a></li>
                        <li><a href="http://framework.zend.com">Zend Framework</a></li>
                        <li><a href="http://www.planet-php.net">Planet-PHP</a></li>
                        <li><a href="http://www.twitter.com/padraicb">I'm on Twitter!</a></li>
                    </ul>
                </nav>
            </section>
        </div>

        <footer id="ft" role="contentinfo">
            <p>Copyright &copy; 2009 Pádraic Brady</p>
            <p>Powered by <a href="http://framework.zend.com">Zend Framework
            </a></p>
        </footer>

    </div>
</body>
</html>
